---
- name: create {{ redhat_agent_path }} directory
  file:
    path: '{{ redhat_agent_path }}'
    recurse: yes
    state: directory
    mode: '0755'

- name: copy agent_config to {{ redhat_agent_path }} directory
  get_url:
    url: '{{ fireeye_agent_config_url }}'
    dest: '{{ redhat_agent_path }}/agent_config.json'
    mode: '0755'

- name: install fireeye agent (redhat)
  yum:
    name: '{{ redhat_fireeye_agent_url }}'
    state: present
