---
- name: create {{ lin_agent_path }} directory
  file:
    path: '{{ lin_agent_path }}'
    state: directory
    mode: '0755'

- name: checking for installer
  stat:
    path: '{{ lin_agent_path }}{{ redhat_fireye_agent_filename }}'
  register: installer

- name: move installer to {{ lin_agent_path }} directory
  copy:
    src: '{{ lin_agent_path }}/{{ item.name }}'
    dest: '{{ lin_agent_path }}/{{ item.name }}'
    mode: '0755'
  with_items:
    - { name: '{{ redhat_fireeye_agent_filename }}'}
  when: not installer.stat.exists

- name: install fireeye agent (redhat)
  yum:
    name: '{{ lin_agent_path }}/{{ item.name }}'
    state: present
  with_items:
    - { name: '{{ redhat_fireeye_agent_filename }}'}
