---
- name: create {{ lin_agent_path }} directory
  file:
    path: '{{ lin_agent_path }}'
    state: directory
    mode: '0755'

- name: checking for installer
  stat:
    path: '{{ lin_agent_path }}{{ redhat_fireye_agent_filename }}'
  register: installer

- name: install fireeye agent (redhat)
  yum:
    name: '{{ lin_agent_path }}/{{ item.name }}'
    state: present
    validate_certs: no
    disable_plugin: "yum-rhn-plugin"
    disablerepo: "rhel-8-appstream-rhui-rpms,rhel-8-baseos-rhui-rpms,rhui-client-config-server-8"
    timeout: 600
  when: path.stat.islnk is not defined

- name: verify fireeye started
  service:
    name: xagt
    state: started
