---
- name: checking for agent install
  stat:
    path: '{{ redhat_fireeye_agent_path }}/bin/xagt'
  register: agent

- debug:
    msg: "fireeye agent not found (installing)"
  when: not agent.stat.exists

- debug:
    msg: "fireeye agent found (skipping install)"
  when: agent.stat.exists

- name: install fireeye agent (redhat)
  yum:
    name: '{{ redhat_fireeye_agent_url }}'
    state: present
    validate_certs: no
    disable_plugin: "yum-rhn-plugin"
    disablerepo: "*"
    download_dir: '{{ redhat_fireeye_agent_path }}'
  when: not agent.stat.exists

- name: copy agent_config.json to {{ redhat_fireeye_agent_path }} directory
  get_url:
    url: '{{ fireeye_agent_config_url }}'
    dest: '{{ redhat_fireeye_agent_path }}/agent_config.json'
    validate_certs: no
    mode: '0755'
  when: not agent.stat.exists

- name: point {{ redhat_fireeye_agent_path }}/bin/xagt to {{ redhat_fireeye_agent_path }}/agent_config.json
  command: '{{ redhat_fireeye_agent_path }}/bin/xagt -i {{ redhat_fireeye_agent_path }}/agent_config.json'
  register: fireeye
  become: yes
  changed_when: fireeye.stdout == "Failed"

- name: verify fireeye started
  service:
    name: xagt
    state: started
