---
- name: create {{ windows_agent_log }} directory
  win_file:
    path: '{{ windows_agent_log }}'
    recurse: yes
    state: directory

- name: create {{ windows_agent_path }} directory
  win_file:
    path: '{{ windows_agent_path }}'
    recurse: yes
    state: directory

- name: copy agent_config.json to {{ windows_agent_path }} directory
  win_get_url:
    url: '{{ fireye_agent_config_url }}'
    dest: '{{ windows_agent_path }}\\agent_config.json'
    mode: '0755'

- name: install fireeye agent (windows)
  win_package:
    path: '{{ windows_fireeye_agent_url }}'
    log_path: '{{ windows_agent_log }}\\fireeye_log.txt'
    validate_certs: no
    state: present
    arguments: /qn
