---
- name: checking for agent install
  win_service:
    name: xagt
  register: agent

- debug:
    msg: "fireeye agent not found (installing)"
  when: not agent.exists

- debug:
    msg: "fireeye agent found (skipping install)"
  when: agent.exists

- name: create {{ windows_agent_log }} directory
  win_file:
    path: '{{ windows_agent_log }}'
    recurse: yes
    state: directory
  when: not agent.exists

- name: create {{ windows_fireeye_agent_path }} directory
  win_file:
    path: '{{ windows_fireeye_agent_path }}'
    recurse: yes
    state: directory
  when: not agent.exists

- name: create {{ windows_fireeye_config_path }} directory
  win_file:
    path: '{{ windows_fireeye_config_path }}'
    recurse: yes
    state: directory
  when: not agent.exists

- name: copy agent_config.json to {{ windows_fireeye_config_path }} directory
  win_get_url:
    url: '{{ fireeye_agent_config_url }}'
    dest: '{{ windows_fireeye_config_path }}\agent_config.json'
    timeout: 600
  when: not agent.exists

- name: install fireeye agent (windows)
  win_package:
    path: '{{ windows_fireeye_agent_url }}'
    log_path: '{{ windows_agent_log }}\fireeye_log.txt'
    product_id: '{{ windows_fireeye_product_id }}'
    chdir: '{{ windows_fireeye_agent_path }}'
    state: present
    arguments: /qn
  when: not agent.exists

- name: verify fireeye started
  win_service:
    name: xagt
    state: started
    start_mode: auto
