---
- name: checking for agent install
  win_stat:
    path: '{{ windows_fireeye_agent_path }}'
  register: path

- debug:
    msg: "fireeye agent not found"
  when: path.stat.islnk is not defined

- debug:
    msg: "fireye agent found skipping install"
  when: path.stat.islnk is defined

- name: create {{ windows_agent_log }} directory
  win_file:
    path: '{{ windows_agent_log }}'
    recurse: yes
    state: directory
  when: path.stat.islnk is not defined

- name: create {{ windows_fireeye_agent_path }} directory
  win_file:
    path: '{{ windows_fireeye_agent_path }}'
    recurse: yes
    state: directory
  when: path.stat.islnk is not defined

- name: copy agent_config.json to {{ windows_fireeye_agent_path }} directory
  win_get_url:
    url: '{{ fireeye_agent_config_url }}'
    dest: '{{ windows_fireeye_agent_path }}\\agent_config.json'
    validate_certs: no
  when: path.stat.islnk is not defined

- name: install fireeye agent (windows)
  win_package:
    path: '{{ windows_fireeye_agent_url }}'
    log_path: '{{ windows_agent_log }}\\fireeye_log.txt'
    product_id: '{{ windows_fireeye_product_id }}'
    chdir: '{{ windows_fireeye_agent_path }}'
    validate_certs: no
    state: present
    arguments: /qn
  when: path.stat.islnk is not defined

- name: verify solarwinds started
  win_service:
    name: xagt
    state: started
